FROM rust:1.65.0

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
RUN rm src/*.rs

COPY . .
RUN rm ./target/release/deps/bcm*
RUN cargo build --release
RUN cp ./target/release/bcm /usr/local/bin

ENTRYPOINT ["bcm", "server", "--host", "0.0.0.0", "--port", "8080" ]
